#----------

# FROM python:$VERSION-alpine AS base
FROM python:3.6-alpine

RUN mkdir -p /app/
WORKDIR /app/

COPY ./Pipfile ./
RUN apk update && \
    apk add --no-cache postgresql-dev gcc python3-dev musl-dev && \
    pip install --no-cache-dir pipenv && \
    pipenv install 

# RUN pipenv lock && pipenv install

#----------

# FROM python:$VERSION-alpine
# 
# COPY --from=builder /go/src/github.com/alexellis/href-counter/app .
